# docker-compose.yml
version: '3.9'

services:
  backend:
    build: ./
    container_name: mr-app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
